apiVersion: v1
kind:  Namespace
metadata:
  name:  frontend
  labels:
    role: frontend
---
apiVersion: v1
kind: Namespace
metadata: 
  name:  frontend
  namespace:  frontend
---
apiVersion: v1
kind:  ServiceAccount
metadata:
  name: frontend
  namespace: frontend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: frontend
rules:
- apiGroups: [""]
  resource: ["endpoints"]
  verbs: ["get"]
---
apiVersion:  rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: Role
  name: frontend
subjects:
- kind: ServiceAccount
  name: frontend
  namespace: frontend
---
apiVersion: ServiceAccount
kind: ServiceAccount
metadata:
  name: backend
  namespace: backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  frontend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: frontend
subjects:
- kind: ServiceAccount
  name: frontend
  namespace: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend
subjects:
- kind: ServiceAccount
  name: backend
  namespace: backend
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-network-policy
  namespace: frontend
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - {}
  ingress:
  - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-network-policy
  namespace: backend
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          role: "frontend"
    - namespaceSelector:
        matchLabels:
          role: "backend"
    - namespaceSelector:
        matchLabels:
          role: "monitoring"
---
apiVersion: v1
kind: Secret
metadata:
  name: xe
  namesapce: backend
type: Opaque
data:
  apikey: {{ .Values.xe.apikey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jackpot-XXXXXX-XXXXXX
  namespace: backend
type: Opaque
data:
  application-connectionstring: {{ .Values.sql.jackpot_XXXXXXX_XXXXXXX | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: frontend
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "{{ .Values.docker_host }}": {
            "auth": {{ Values.docker.auth | b64enc | quote }}
            }
          }
        }
---
